name: Run checks on frontend

on:
  pull_request:
    branches:
      - "main"
      - "add-pipelines"

jobs:
  build:
    name: Run code tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build -t local ./consumer
      - name: Run Linting
        run: docker run local npm run lint
